---
- name: Configure base packages on all prod servers
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common
    - docker

- name: Deploy frontend on prod
  hosts: frontend
  become: true
  gather_facts: true
  roles:
    - role: frontend
      when: deploy_apps | default(false) | bool

- name: Deploy backend on prod
  hosts: backend
  become: true
  gather_facts: true
  roles:
    - role: backend
      when: deploy_apps | default(false) | bool
